services:
  php:
    container_name: ${COMPOSE_PREFIX}php
    build: ./.docker/php
    volumes:
      # Data and Logs
      - ./data/:/data/
      - ./logs/:/logs/
      # Dev
      - ./.docker/php/os/docker/:/docker/
      - ./.docker/php/os/adm/:/adm/
      - ./.docker/php/apache/httpd.conf:/etc/apache2/httpd.conf
      - ./.docker/php/php/php.ini:/etc/php81/php.ini
      # Application
      - ./src/:/app/
    ports:
      # Web Server
      - "80:80"
      - "443:443"
      # XDebug
      - "10000:10000"